import { customGroup } from './custom'
import type { SetType } from './types'

export interface LibraryExercise {
  name: string
  type: SetType
  group: string
}

// name|type, grouped by muscle group. Type drives which inputs a set row shows.
const RAW: Record<string, string[]> = {
  Chest: [
    'Barbell Bench Press|W',
    'Incline Barbell Bench Press|W',
    'Decline Barbell Bench Press|W',
    'Dumbbell Bench Press|W',
    'Incline Dumbbell Press|W',
    'Decline Dumbbell Press|W',
    'Machine Chest Press|W',
    'Incline Machine Press|W',
    'Smith Machine Bench Press|W',
    'Smith Machine Incline Press|W',
    'Hammer Strength Chest Press|W',
    'Cable Fly|W',
    'Low to High Cable Fly|W',
    'High to Low Cable Fly|W',
    'Dumbbell Fly|W',
    'Incline Dumbbell Fly|W',
    'Pec Deck|W',
    'Push Up|R',
    'Weighted Push Up|W',
    'Deficit Push Up|R',
    'Dip|R',
    'Weighted Dip|W',
    'Svend Press|W',
  ],
  Back: [
    'Deadlift|W',
    'Trap Bar Deadlift|W',
    'Rack Pull|W',
    'Barbell Row|W',
    'Pendlay Row|W',
    'Dumbbell Row|W',
    'Chest Supported Row|W',
    'Seal Row|W',
    'T Bar Row|W',
    'Seated Cable Row|W',
    'Wide Grip Cable Row|W',
    'Single Arm Cable Row|W',
    'Machine Row|W',
    'Hammer Strength Row|W',
    'Meadows Row|W',
    'Pull Up|R',
    'Weighted Pull Up|W',
    'Chin Up|R',
    'Weighted Chin Up|W',
    'Neutral Grip Pull Up|R',
    'Lat Pulldown|W',
    'Wide Grip Lat Pulldown|W',
    'Close Grip Lat Pulldown|W',
    'Single Arm Lat Pulldown|W',
    'Straight Arm Pulldown|W',
    'Cable Pullover|W',
    'Dumbbell Pullover|W',
    'Machine Pullover|W',
    'Inverted Row|R',
    'Back Extension|R',
    'Weighted Back Extension|W',
    'Reverse Hyper|W',
  ],
  Shoulders: [
    'Overhead Press|W',
    'Seated Barbell Press|W',
    'Dumbbell Shoulder Press|W',
    'Seated Dumbbell Press|W',
    'Arnold Press|W',
    'Machine Shoulder Press|W',
    'Smith Machine Shoulder Press|W',
    'Landmine Press|W',
    'Push Press|W',
    'Z Press|W',
    'Lateral Raise|W',
    'Cable Lateral Raise|W',
    'Machine Lateral Raise|W',
    'Leaning Lateral Raise|W',
    'Front Raise|W',
    'Pike Push Up|R',
    'Handstand Push Up|R',
    'Plate Front Raise|W',
    'Rear Delt Fly|W',
    'Cable Rear Delt Fly|W',
    'Reverse Pec Deck|W',
    'Face Pull|W',
    'Upright Row|W',
  ],
  Traps: [
    'Barbell Shrug|W',
    'Dumbbell Shrug|W',
    'Trap Bar Shrug|W',
    'Cable Shrug|W',
    'Machine Shrug|W',
    'Smith Machine Shrug|W',
    'Snatch Grip High Pull|W',
    'Kelso Shrug|W',
  ],
  Biceps: [
    'Barbell Curl|W',
    'EZ Bar Curl|W',
    'Dumbbell Curl|W',
    'Alternating Dumbbell Curl|W',
    'Incline Dumbbell Curl|W',
    'Hammer Curl|W',
    'Cross Body Hammer Curl|W',
    'Preacher Curl|W',
    'Machine Preacher Curl|W',
    'Cable Curl|W',
    'Rope Cable Curl|W',
    'Bayesian Cable Curl|W',
    'Concentration Curl|W',
    'Spider Curl|W',
    'Drag Curl|W',
    'Zottman Curl|W',
    '21s|W',
  ],
  Triceps: [
    'Close Grip Bench Press|W',
    'Skull Crusher|W',
    'EZ Bar Skull Crusher|W',
    'Dumbbell Skull Crusher|W',
    'Overhead Cable Extension|W',
    'Rope Overhead Extension|W',
    'Single Arm Overhead Extension|W',
    'Dumbbell Overhead Extension|W',
    'Triceps Pushdown|W',
    'Rope Pushdown|W',
    'V Bar Pushdown|W',
    'Reverse Grip Pushdown|W',
    'Cable Kickback|W',
    'Dumbbell Kickback|W',
    'JM Press|W',
    'Bench Dip|R',
    'Diamond Push Up|R',
  ],
  Forearms: [
    'Wrist Curl|W',
    'Reverse Wrist Curl|W',
    'Behind Back Wrist Curl|W',
    'Reverse Curl|W',
    'Plate Pinch|T',
    'Dead Hang|T',
    'Wrist Roller|T',
    'Grip Crusher|R',
  ],
  Quads: [
    'Back Squat|W',
    'Front Squat|W',
    'Goblet Squat|W',
    'Bodyweight Squat|R',
    'Hack Squat|W',
    'Machine Hack Squat|W',
    'Belt Squat|W',
    'Leg Press|W',
    'Single Leg Press|W',
    'Leg Extension|W',
    'Single Leg Extension|W',
    'Bulgarian Split Squat|W',
    'Split Squat|W',
    'Walking Lunge|W',
    'Reverse Lunge|W',
    'Step Up|W',
    'Sissy Squat|R',
    'Smith Machine Squat|W',
    'Cyclist Squat|W',
    'Wall Sit|T',
  ],
  Hamstrings: [
    'Romanian Deadlift|W',
    'Dumbbell Romanian Deadlift|W',
    'Single Leg Romanian Deadlift|W',
    'Stiff Leg Deadlift|W',
    'Good Morning|W',
    'Lying Leg Curl|W',
    'Seated Leg Curl|W',
    'Standing Leg Curl|W',
    'Single Leg Curl|W',
    'Nordic Curl|R',
    'Glute Ham Raise|R',
    'Cable Pull Through|W',
  ],
  Glutes: [
    'Hip Thrust|W',
    'Single Leg Hip Thrust|W',
    'Machine Hip Thrust|W',
    'Glute Bridge|W',
    'Cable Glute Kickback|W',
    'Machine Glute Kickback|W',
    'Hip Abduction|W',
    'Standing Hip Abduction|W',
    'Frog Pump|R',
    'Curtsy Lunge|W',
  ],
  Calves: [
    'Standing Calf Raise|W',
    'Seated Calf Raise|W',
    'Leg Press Calf Raise|W',
    'Smith Machine Calf Raise|W',
    'Single Leg Calf Raise|W',
    'Donkey Calf Raise|W',
    'Tibialis Raise|R',
    'Jump Rope|T',
  ],
  Core: [
    'Plank|T',
    'Side Plank|T',
    'RKC Plank|T',
    'Hollow Body Hold|T',
    'Copenhagen Plank|T',
    'Hanging Leg Raise|R',
    'Hanging Knee Raise|R',
    'Captains Chair Leg Raise|R',
    'Lying Leg Raise|R',
    'Cable Crunch|W',
    'Machine Crunch|W',
    'Crunch|R',
    'Bicycle Crunch|R',
    'Sit Up|R',
    'Weighted Sit Up|W',
    'Decline Sit Up|R',
    'Ab Wheel Rollout|R',
    'Pallof Press|W',
    'Cable Woodchop|W',
    'Russian Twist|R',
    'Dead Bug|R',
    'Bird Dog|R',
    'V Up|R',
    'Toes to Bar|R',
    'Dragon Flag|R',
  ],
  Carries: [
    'Farmer Carry|WD',
    'Suitcase Carry|WD',
    'Front Rack Carry|WD',
    'Overhead Carry|WD',
    'Trap Bar Carry|WD',
    'Sandbag Carry|WD',
    'Sled Push|WD',
    'Sled Drag|WD',
    'Yoke Walk|WD',
  ],
  Cardio: [
    'Run|C',
    'Jog|C',
    'Treadmill Run|C',
    'Incline Walk|C',
    'Walk|C',
    'Sprints|C',
    'Row Erg|C',
    'Ski Erg|C',
    'Assault Bike|C',
    'Stationary Bike|C',
    'Cycling|C',
    'Elliptical|C',
    'Stair Climber|C',
    'Swim|C',
  ],
}

export const MUSCLE_GROUPS = Object.keys(RAW)

export const LIBRARY: LibraryExercise[] = MUSCLE_GROUPS.flatMap((group) =>
  RAW[group].map((entry) => {
    const [name, type] = entry.split('|')
    return { name, type: type as SetType, group }
  }),
)

const BY_NAME = new Map(LIBRARY.map((e) => [e.name.toLowerCase(), e]))

export function lookupType(name: string): SetType | null {
  return BY_NAME.get(name.trim().toLowerCase())?.type ?? null
}

export function groupOf(name: string): string | null {
  const own = customGroup(name)
  if (own) return own
  return BY_NAME.get(name.trim().toLowerCase())?.group ?? null
}

export type Equipment = 'barbell' | 'dumbbell' | 'machine' | 'cable' | 'bodyweight' | 'other'

// Names the keyword rules below get wrong.
const EQUIPMENT_OVERRIDES: Record<string, Equipment> = {
  'Dip': 'bodyweight',
  'Weighted Dip': 'bodyweight',
  'Bench Dip': 'bodyweight',
  'Goblet Squat': 'dumbbell',
  'Bodyweight Squat': 'bodyweight',
  'Sissy Squat': 'bodyweight',
  'Wall Sit': 'bodyweight',
  'Belt Squat': 'machine',
  'Leg Press': 'machine',
  'Single Leg Press': 'machine',
  'Leg Press Calf Raise': 'machine',
  'Hack Squat': 'machine',
  'Pec Deck': 'machine',
  'Reverse Pec Deck': 'machine',
  'Hip Abduction': 'machine',
  'Standing Hip Abduction': 'machine',
  'Reverse Hyper': 'machine',
  'Glute Ham Raise': 'bodyweight',
  'Nordic Curl': 'bodyweight',
  'Back Extension': 'bodyweight',
  'Inverted Row': 'bodyweight',
  'Frog Pump': 'bodyweight',
  'Glute Bridge': 'bodyweight',
  'Single Leg Calf Raise': 'bodyweight',
  'Tibialis Raise': 'bodyweight',
  'Dead Hang': 'bodyweight',
  'Jump Rope': 'bodyweight',
  'Hip Thrust': 'barbell',
  'Single Leg Hip Thrust': 'bodyweight',
  'Trap Bar Carry': 'barbell',
  'Farmer Carry': 'dumbbell',
  'Suitcase Carry': 'dumbbell',
  'Front Rack Carry': 'dumbbell',
  'Overhead Carry': 'dumbbell',
  'Sandbag Carry': 'other',
  'Yoke Walk': 'other',
  'Plate Pinch': 'other',
  'Wrist Roller': 'other',
  'Grip Crusher': 'other',
  'Svend Press': 'other',
  'Landmine Press': 'barbell',
  'Z Press': 'barbell',
  '21s': 'barbell',
}

const BODYWEIGHT_WORDS = [
  'Push Up', 'Pull Up', 'Chin Up', 'Plank', 'Hollow', 'Hanging', 'Sit Up', 'Crunch', 'Russian Twist',
  'Dead Bug', 'Bird Dog', 'V Up', 'Toes to Bar', 'Dragon Flag', 'Ab Wheel', 'Captains Chair',
  'Lying Leg Raise', 'Bicycle', 'Run', 'Jog', 'Walk', 'Sprints', 'Swim',
]

// Derived from the name, which is imprecise but keeps 226 movements from
// needing a hand written tag each. The overrides above carry the exceptions.
export function equipmentOf(name: string): Equipment {
  const n = name.trim()
  if (EQUIPMENT_OVERRIDES[n]) return EQUIPMENT_OVERRIDES[n]
  if (/Machine|Hammer Strength|Smith|Erg|Assault Bike|Stationary Bike|Elliptical|Stair Climber|Treadmill/i.test(n)) return 'machine'
  if (/Cable|Pulldown|Pushdown|Rope|Face Pull|Pull Through|Woodchop|Pallof/i.test(n)) return 'cable'
  if (/Dumbbell|Goblet|Arnold|Concentration|Zottman|Hammer Curl|Cross Body/i.test(n)) return 'dumbbell'
  if (/Barbell|EZ Bar|Trap Bar|Deadlift|Squat|Shrug|Good Morning|Rack Pull|Snatch|Skull Crusher|Upright Row|Overhead Press|Push Press|Bench Press|JM Press|Preacher|Drag Curl|Spider Curl|Reverse Curl|Wrist Curl|Meadows|Seal Row|Pendlay|T Bar/i.test(n)) return 'barbell'
  if (BODYWEIGHT_WORDS.some((w) => n.includes(w))) return 'bodyweight'
  if (/Sled|Cycling/i.test(n)) return 'other'
  return 'dumbbell'
}
